### ISSUE TITLE
Create .password-store on startup if not already present.

### ISSUE THREAD

**Issue by Maesto** [jreinert/autopass#1]
If you install autopass, configure it and just run it you will be greetet by this.

```
[user@host ~]$ autopass
/usr/lib/ruby/2.2.0/fileutils.rb:127:in `chdir': No such file or directory @ dir_chdir - /home/user/.password-store (Errno::ENOENT)
       from /usr/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
       from /usr/bin/autopass:232:in `checksums'
       from /usr/bin/autopass:222:in `update_cache'
       from /usr/bin/autopass:161:in `initialize'
       from /usr/bin/autopass:251:in `new'
       from /usr/bin/autopass:251:in `<main>'
```

a simple

```
[user@host ~]$ mkdir .password-store
```

fixes this. Maybe instead of creating the dir a hint to "pass init" would be preferable. But with a complete config we also have all the data needed for creation.

**Comment by repomaa** [comment]
> But with a complete config we also have all the data needed for creation.

Not quite. `pass init` needs the key id to encrypt for. I could make assumptions that the `cache_key` config value should be used but I'd rather do it the other way around. (use the key id stored in `.password-store .gpg-id` for encrypting the cache)

I will provide a more meaningful error message for uninitialized password stores. But autopass will not create a password store for the user. It is designed to be a read only interface to pass.

**Comment by Maesto** [comment]
> meaningful error message

\o/
