### ISSUE TITLE
optionparser

### ISSUE THREAD

**Issue by bew-dev** [jreinert/autopass#24]
Im getting pretty gridlocked on what may be a bundle issue? 
```
$ autopass
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- optionparser (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/bill/bin/autopass:8:in `<main>'
```
 I dont see any mention of gems here, but when i try to run autopass(not even testing yet if all dependencies are configured, i just got them all installed), i see an optionparser error.  I thought maybe  i needed to make a Gemfile and add in there gem 'OptionParser' and install bundle, however this has not helped, same error.  

What might my RHEL 7.3 need to get over the hump?  Do i need ruby, gem, bundler at all for this app?

Note for future users, for RHEL 7.3 i got a few packages for the dependedncies here
`yum install  libnofity xdotool xclip xorg-x11-utils`

To be honest with you, im not sure where im at, or what to expect, so totally lost, if theres more info i might be missing, im all ears.

**Comment by repomaa** [comment]
hi @bew-dev! First of all thanks for reporting the issue. There was a incorrect require statement in the code. OptionParser is required via 'optparse'. Why it worked for me in the first place is a mystery...
