### ISSUE TITLE
autopass failes to parse twitter handle

### ISSUE THREAD

**Issue by x4121** [jreinert/autopass#25]
When running autopass (current master) I get:

```
Failed parsing entry 'www/twitter.com/@ArminGrodon':
super_secret_password
---
login: @ArminGrodon
url: https://twitter.com
autotype: login :tab pass
(<unknown>): found character that cannot start any token while scanning for the next token at line 2 column 8
./autopass:348:in `basename': no implicit conversion of Hash into String (TypeError)
```

`pass` doesn't have a problem with strings starting with '@' (well, technically it probably just ignores everything past the first line) and `rofi-pass` doesn't either.

**Comment by repomaa** [comment]
yes, you're right. pass doesn't care about anything but the first line, and rofi-pass doesn't use a yaml parser but some home grown solution for parsing the yaml. Long story short. `@` at the beginning of a scalar isn't allowed in yaml so you should just quote it.
