### ISSUE TITLE
Cache_key option not defined

### ISSUE THREAD

**Issue by LiVeenMusic** [jreinert/autopass#26]
After initiating the first time, this is what I get when I type autopass into my terminal, both in sudo and outside sudo:  
  
`@ARCH ~]$ autopass`
`/usr/bin/autopass:302:in `initialize': cache_key option not defined (RuntimeError)`
`	from /usr/bin/autopass:407:in `new'`
`	from /usr/bin/autopass:407:in <main>`

Any idea what it could be?

**Comment by LiVeenMusic** [comment]
Turned out I had been trying to configure the wrong file. I was in /usr/bin/autopass when I should have been in ~/.config/autopass/config.yml all along.

However, after configuring this, I ended up with a whole nother type of error! (sorry if it looks spammy)
  
autopass
Failed parsing entry 'localhost/%':
mypasswordhere
name: localhost
username: %
url: http://localhost/phpmyadmin/
(<unknown>): found character that cannot start any token while scanning for the next token at line 2 column 11
/usr/bin/autopass:348:in `basename': no implicit conversion of Hash into String (TypeError)
	from /usr/bin/autopass:348:in `rescue in entry_from'
	from /usr/bin/autopass:339:in `entry_from'
	from /usr/bin/autopass:380:in `block in update_cache'
	from /usr/bin/autopass:378:in `each'
	from /usr/bin/autopass:378:in `update_cache'
	from /usr/bin/autopass:305:in `initialize'
	from /usr/bin/autopass:407:in `new'
	from /usr/bin/autopass:407:in `<main>'
  
  
Other than this, when I try to run autopass using Rofi, nothing at all appears to happen.

**Comment by LiVeenMusic** [comment]
Update: Did further research, turned out my password-store had some passwords that wouldn't work well with autopass. I used `qtpass` to delete them, and not autopass works just fine. 

Thanks anyways, and I hope this will help someone else! :+1:

**Comment by tasmo** [comment]
Got the same error. What did you do to find the "corrupted" passwords?

**Comment by repomaa** [comment]
It should tell you exactly which entry is causing the crash as @ChrisRonaasen shows in the output. I suppose % as username won't work. Would have to escape it.
