### ISSUE TITLE
Would love to be able to configure the BROWSERS variable

### ISSUE THREAD

**Issue by carlf** [jreinert/autopass#28]
Currently the script has a hardcoded list of browsers in the BROWSERS variable. I use qutebrowser which is not in the list. I can hardcode it into the list but ideally, I'd like to be able to configure this outside of the script.

**Comment by repomaa** [comment]
Thanks for the good idea. You can configure it with the `browsers` config option. (See example config in README). Always nice to help out a fellow qutebrowser user ;)
