### ISSUE TITLE
Delay option while autotyping

### ISSUE THREAD

**Issue by ghost** [jreinert/autopass#31]
Is it possible to get a configurable delay (maybe in ms) in an autotype sequence ?

**Comment by repomaa** [comment]
Sound's like a good idea. You mean something like: `user :delay :tab pass`? And having the length of the delay as a config option?

**Comment by ghost** [comment]
Yes ! It's mostly useful on multiple pages login. Being able to do `user :enter :delay password :enter` would be great

**Comment by repomaa** [comment]
:+1: Definately useful!
