### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by DBLouis** [jreinert/autopass#33]
I can't run your program beside having all the needed dependencies.
If I just try `./bin/autopass` I get:

    Traceback (most recent call last):                                                                                                                                                                                 
        2: from ./bin/autopass:5:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
    /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- autopass/config (LoadError)

**Comment by repomaa** [comment]
I should update the readme. You will have to install the "bundler" gem and install autopass by running `bundle install && bundle exec rake install` in the project root.

Am 14. Oktober 2018 10:03:37 MESZ schrieb LouisDB <notifications@github.com>:
>I can't run your program beside having all the needed dependencies.
>If I just try `./bin/autopass` I get:
>
>Traceback (most recent call last):                                     
>                                                                       
>        2: from ./bin/autopass:5:in `<main>'
>1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in
>`require'
>/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in
>`require': cannot load such file -- autopass/config (LoadError)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jreinert/autopass/issues/33

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DBLouis** [comment]
I had to install the `ruby-devel` package (voidlinux) to run `bundle install` successfully.
~~However the second command is not working~~ It just needed root permissions.

Thank you

**Comment by repomaa** [comment]
Closing this. Opened #35 instead.
