### ISSUE TITLE
Public key not found

### ISSUE THREAD

**Issue by DBLouis** [jreinert/autopass#34]
When I run autopass the first time, after updating cache it fails with this message:

    autopass 
    Updating cache...
    [################################################ ]
    gpg: xxxxxxx: skipped: public key not found
    gpg: [stdin]: encryption failed: public key not found

I tried both long and short format for the key ID. Also I am using subkeys.

Maybe autopass uses gpg1 and not gpg2?

**Comment by repomaa** [comment]
Looks like a gpg error. Can you encrypt things with the key you set as cache key as recepient from the command line?

Am 14. Oktober 2018 13:18:58 MESZ schrieb LouisDB <notifications@github.com>:
>When I run autopass the first time, after updating cache it fails with
>this message:
>
>    autopass 
>    Updating cache...
>    [################################################ ]
>    gpg: xxxxxxx: skipped: public key not found
>    gpg: [stdin]: encryption failed: public key not found
>
>I tried both long and short format for the key ID. Also I am using
>subkeys.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jreinert/autopass/issues/34

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DBLouis** [comment]
The command is hard-coded so I just changed it to gpg2 instead and it seems to work.
Maybe you should add an option to choose between gpg 1 and 2 in the config file.
