### ISSUE TITLE
Copy password not working

### ISSUE THREAD

**Issue by DBLouis** [jreinert/autopass#38]
The copy password command does nothing except displaying a notification.
I have xclip installed.

**Comment by DBLouis** [comment]
This is actually working but I have to maintain shift to make it work because I have a french  keyboard layout. Is this intended behavior? Is it possible to change the shortcut for copy autotype_x?

**Comment by repomaa** [comment]
@DBLouis yes, it's possible. In your config add something like:

``` yaml
key_bindings:
  copy_password: 'Alt+c'
```

See the rofi manpage for possible key bindings.

**Comment by DBLouis** [comment]
Sorry I was asking about changing the shortcut for autotypes. Copy password is still not working, it only displays a notification but the password is not copied into the clipboard.

**Comment by repomaa** [comment]
I'm pretty sure it's copied into the clipboard, but maybe not into the selection you're expecting. I'm sorry if I'm stating obvious things here, but I want to be sure we leave no stone unturned. The X clipboard has two "selections": primary and clipboard. Autopass will copy passwords and usernames to the primary selection. You can paste from this selection using your middle mouse button or shift+insert.

**Comment by DBLouis** [comment]
It seems to work. Thank you. Maybe you should add this to the readme because it is not obvious.

**Comment by repomaa** [comment]
@DBLouis indeed i should, btw, if you don't like the current behavior you're free to change this with the (also poorly documented) config setting: `clip_command`. Change it to `clip -selection clipboard` to use the clipboard selection.

**Comment by repomaa** [comment]
@DBLouis due to current lack of documentation, check out https://github.com/jreinert/autopass/blob/master/lib/autopass/config.rb for all available config options.
